# first, install Cypress, then run all tests
stages:
  - build
  - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
  REQUIRED_ENVIRONMENT: "test"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# this job installs NPM dependencies and Cypress
install:
  image: cypress/base:10
  stage: build

  script:
    - yarn install
    # show where the Cypress test runner binaries are cached
    - $(npm bin)/cypress cache path
    # show all installed versions of Cypress binary
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify

# job that runs after "install" job finishes
# NPM dependencies and Cypress binary should be already installed
# This is extendable body of job
.cypress:
  image: cypress/base:10
  stage: test
  environment:
    name: $REQUIRED_ENVIRONMENT
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - cypress/screenshots
      - cypress/videos
  before_script:
    - echo "Running test against environment ${DYNAMIC_ENVIRONMENT}."
    - echo "CYPRESS_DM_BASE_URL is ${CYPRESS_DM_BASE_URL}.".

# Job which should run in typical way by committing directly in this repository
cypress-e2e:test:
  extends: .cypress
  except:
    variables:
      - $APPLICATION_DM
      - $APPLICATION_NCDB
      - $APPLICATION_OO2
  script:
    # the free cypress record limit is 500 recorded tests per month
    # if we upgrade our billing plan to 99$/month we can implement
    # test recording at cypess dashboard use several parallel runs
    # to run tests with recording use:
    # - $(npm bin)/cypress run --record
    # record key for this project is: 974ddd92-4fbd-4a3e-9b1e-67ee7e0ab426
    - $(npm bin)/cypress run --browser chrome

# Jobs which should run by multiproject-pipeline from another projects running only exact group of tests
cypress-e2e:test:dm:
  extends: .cypress
  only:
    variables:
      - $APPLICATION_DM == "true"
  script:
    - $(npm bin)/cypress run --browser chrome --spec "cypress/integration/DM/**/*"

cypress-e2e:test:ncdb:
  extends: .cypress
  only:
    variables:
      - $APPLICATION_NCDB == "true"
  script:
    - $(npm bin)/cypress run --browser chrome --spec "cypress/integration/NCDB/**/*"

cypress-e2e:test:oo2:
  extends: .cypress
  only:
    variables:
      - $APPLICATION_OO2 == "true"
  script:
    - $(npm bin)/cypress run --browser chrome --spec "cypress/integration/OO2/**/*"
