export default {
  dashboardPage: '/pages/dashboard',
  orderCreatePage: '/pages/orders/orderCreate',
  actionSelectionPage: '/pages/orders/wizard/actionSelection',
  cardTypeSelectionPage: '/pages/orders/wizard/cardTypeSelection',
  cardHolderSelectionPage: '/pages/orders/wizard/cardHolderSelection',
  cardOwnerFormPage: '/pages/cardOwners/cardOwnerForm',
  orderCreateEntriesPage: '/pages/orders/orderCreateEntries',
  orderDetailPage: '/pages/orders/orderDetail',
  orderListPage: '/pages/orders/orderList.jsf',
  loginPage: '/login.jsf',
  personalDataPage: '/ordering/personal-data',
  additionalProductsPage: '/ordering/additional-products',
  overviewPage: '/ordering/overview',
  orderCreateInsuranceEntries: '/pages/orders/orderCreateInsuranceEntries',
  adminCardOrdersDetail: '/administration/cardOrders',
  adminOO2LoginPage: '/administration/security/login',
  adminDMLoginPage: '/security/login',
};
